# Generated by Django 2.2.5 on 2020-05-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_auto_20200225_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=500)),
                ('s_area', models.CharField(blank=True, max_length=500)),
                ('s_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='images/mehul.png', upload_to='my_app/img/'),
        ),
    ]
