# Generated by Django 3.0.8 on 2020-07-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ColorVariation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SizeVariation')),
            ],
        ),
    ]
