# Generated by Django 3.0.7 on 2020-06-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20)),
                ('catdiscription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('speciality', models.CharField(blank=True, max_length=60)),
                ('contact', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.FileField(default='bg_1.jpg', upload_to='images/')),
                ('status', models.CharField(blank=True, default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.CharField(max_length=500)),
                ('pquantity', models.IntegerField(default=0)),
                ('pprice', models.IntegerField(default=0)),
                ('pexpiredate', models.DateField()),
                ('profile_pic', models.FileField(default='bg_1.jpg', upload_to='images/')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('brandname', models.CharField(max_length=50)),
                ('brandlogo', models.FileField(default='companylogo.png', upload_to='adminpanel/images/')),
                ('contactno', models.CharField(blank=True, max_length=500)),
                ('websiteaddress', models.CharField(blank=True, max_length=500)),
                ('profile_pic', models.FileField(default='Admin.png', upload_to='adminpanel/images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(default='Admin.png', upload_to='adminpanel/images/')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Area')),
            ],
        ),
        migrations.CreateModel(
            name='yogavideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='video/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.User')),
            ],
        ),
        migrations.CreateModel(
            name='placeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=150)),
                ('status', models.CharField(default='In Process', max_length=50)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.User')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimage', models.CharField(max_length=50)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.User')),
            ],
        ),
        migrations.CreateModel(
            name='addToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.User')),
            ],
        ),
    ]
