# Generated by Django 2.2.3 on 2019-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190725_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
    ]
